---
- name: Add SBT repo
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present update_cache=no
- name: Add SBT repo key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id='2EE0EA64E40A89B84B2DF73499E82A75642AC823'
- name: Install SBT
  apt: name=sbt state=present update_cache=yes
